# Palo Alto Parameter Checker - 새로운 구조 설정 파일
# 이 파일은 기존의 복잡한 4개 섹션을 하나로 통합한 개선된 구조입니다.

parameters:
  # CTD 모드 설정 확인
  - name: "ctd_mode"
    description: "Content-ID 확인 모드 설정 - 성능 최적화를 위해 비활성화 권장"
    expected_value: "disabled"
    api_command: "show system setting ctd mode"
    cli_query_command: "show system setting | match ctd"
    cli_modify_command: "set system setting ctd-mode disabled"
    output_prefix: "CTD mode is:"

  # 애플리케이션 재매칭 설정
  - name: "rematch"
    description: "애플리케이션 재매칭 설정 - 성능 영향으로 비활성화 권장"
    expected_value: "disabled"
    api_command: "show config running match rematch"
    cli_query_command: "show running application setting | match rematch"
    cli_modify_command: "set application setting rematch disabled"
    output_prefix: "Rematch:"

  # 세션 타임아웃 설정
  - name: "session_timeout"
    description: "세션 타임아웃 설정 - 적절한 타임아웃으로 리소스 관리"
    expected_value: "3600"
    api_command: "show system setting session timeout"
    cli_query_command: "show system setting | match timeout"
    cli_modify_command: "set system setting session timeout 3600"
    output_prefix: "Session timeout:"

  # 시스템 로그 레벨
  - name: "log_level"
    description: "시스템 로그 레벨 - 정보성 로그로 설정하여 적절한 로깅 유지"
    expected_value: "informational"
    api_command: "show system setting log level"
    cli_query_command: "show system setting | match log-level"
    cli_modify_command: "set system setting log-level informational"
    output_prefix: "Log level:"

  # SSL 복호화 설정 (예시)
  - name: "ssl_decrypt"
    description: "SSL 복호화 기능 설정 - 보안 정책에 따라 활성화/비활성화"
    expected_value: "enabled"
    api_command: "show system setting ssl-decrypt"
    cli_query_command: "show system setting | match ssl"
    cli_modify_command: "set system setting ssl-decrypt enabled"
    output_prefix: "SSL decrypt:"

  # 위협 탐지 설정 (예시)
  - name: "threat_detection"
    description: "위협 탐지 엔진 설정 - 보안을 위해 활성화 권장"
    expected_value: "enabled"
    api_command: "show system setting threat-detection"
    cli_query_command: "show system setting | match threat"
    cli_modify_command: "set system setting threat-detection enabled"
    output_prefix: "Threat detection:"

# 장점:
# 1. 모든 파라미터 정보가 한 곳에 집중되어 관리가 쉬움
# 2. 새로운 파라미터 추가 시 단일 블록만 추가하면 됨
# 3. CLI 명령어 정보도 함께 관리되어 운영 효율성 향상
# 4. 기존 로직과 100% 호환됨 (어댑터를 통한 투명한 변환)
# 5. 각 파라미터별 설명으로 가독성 향상