parameters:
  - name: "ctd_mode"
    description: "Content-ID 확인 모드 설정"
    expected_value: "disabled"
    query_command: "show system setting ctd mode"
    modify_command: "set system setting ctd-mode disabled"
    match_pattern: "CTD mode is: (\\S+)"

  - name: "rematch"
    description: "애플리케이션 재매칭 설정"
    expected_value: "yes"
    query_command: "show running application-override | match rematch"
    modify_command: "set application setting rematch yes"
    match_pattern: "rematch\\s+(\\S+)"

  - name: "session_timeout"
    description: "세션 타임아웃 설정 (분)"
    expected_value: "60"
    query_command: "show system setting session | match timeout"
    modify_command: "set system setting session timeout 60"
    match_pattern: "timeout:\\s+(\\d+)"

  - name: "dns_servers"
    description: "DNS 서버 설정"
    expected_value: ["8.8.8.8", "8.8.4.4"]
    query_command: "show system info | match DNS"
    modify_command: "set system dns-setting servers primary 8.8.8.8 secondary 8.8.4.4"
    match_pattern: "DNS:\\s+([\\d\\.\\s,]+)"
    separator: ","
    multi_result: true

  - name: "ntp_servers"
    description: "NTP 서버 설정"
    expected_value: ["time.nist.gov", "pool.ntp.org"]
    query_command: "show ntp"
    modify_command: "set system ntp-servers primary-ntp-server time.nist.gov secondary-ntp-server pool.ntp.org"
    match_pattern: "Server:\\s+([\\w\\.\\-]+)"
    multi_result: true

  - name: "admin_lockout_time"
    description: "관리자 계정 잠금 시간 설정 (분)"
    expected_value: "30"
    query_command: "show config running setting | match lockout"
    modify_command: "set mgt-config users admin lockout-time 30"
    match_pattern: "lockout-time\\s+(\\d+)"

  - name: "ssl_decrypt"
    description: "SSL/TLS 복호화 설정"
    expected_value: "enabled"
    query_command: "show system setting ssl-decrypt | head -10"
    modify_command: "set system setting ssl-decrypt enable"
    match_pattern: "SSL decrypt:\\s+(\\w+)"

  - name: "threat_prevention_policies"
    description: "위협 방지 정책 목록"
    expected_value: ["strict", "balanced"]
    query_command: "show profiles virus list | match name"
    modify_command: "configure; set profiles virus [policy-name] action block"
    match_pattern: "name\\s+([\\w\\-]+)"
    multi_result: true

  - name: "log_forwarding"
    description: "로그 전달 설정"
    expected_value: "enabled"
    query_command: "show log-settings system | match forwarding"
    modify_command: "set log-settings system match-list [name] send-to-panorama yes"
    match_pattern: "forwarding:\\s+(\\w+)"

  - name: "interface_status"
    description: "인터페이스 상태 확인"
    expected_value: ["up", "up", "up"]
    query_command: "show interface all | match -A 1 'State:'"
    modify_command: "configure; set network interface [interface-name] link-state up"
    match_pattern: "State:\\s+(\\w+)"
    multi_result: true