parameters:
  - name: "ctd_mode"
    description: "Content-ID 확인 모드 설정"
    expected_value: "disabled"
    api_command: "show system setting ctd mode"
    output_prefix: "CTD mode is:"
    cli_query_command: "show system setting | match ctd"
    cli_modify_command: "set system setting ctd-mode disabled"

  - name: "rematch"
    description: "애플리케이션 재매칭 설정"
    expected_value: "yes"
    api_command: "show config running match rematch"
    output_prefix: "rematch:"
    cli_query_command: "show running application setting | match rematch"
    cli_modify_command: "set application setting rematch yes"

  - name: "session_timeout"
    description: "세션 타임아웃 설정"
    expected_value: "60"
    api_command: "show system setting session timeout"
    output_prefix: "Session timeout:"
    cli_query_command: "show system setting | match timeout"
    cli_modify_command: "set system setting session timeout 60" 